### ISSUE TITLE
Practica de validación de propuesta de valor

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-tecnopower#2]
[PRACTICA1_INGENERIA_DE_SOFTWARE .pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-tecnopower/files/8127111/PRACTICA1_INGENERIA_DE_SOFTWARE.pdf)

**Comment by CxrlosMX** [comment]
Bien realizado, calificación: 20%

**Comment by josealfredo79** [comment]
Falta el lienzo de la propuesta de valor

**Comment by josealfredo79** [comment]
Agregarlo por favor. Bien hecho y liberado
